[package]
name = "calendar-tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
chrono = "0.4.24"
colored = "2"
crossterm = "0.26.1"
itertools = "0.10.5"
